# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kmilchev <kmilchev@student.42wolfsburg.de> +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/07 11:55:48 by kmilchev          #+#    #+#              #
#    Updated: 2022/04/07 12:34:50 by kmilchev         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# one:
# 	gcc k_readline.c -lreadline libft.a && ./a.out

signals:
	gcc k_signals.c -lreadline libft.a && ./a.out