# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kmilchev <kmilchev@student.42wolfsburg.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/07 11:55:48 by kmilchev          #+#    #+#              #
#    Updated: 2022/04/08 15:23:04 by kmilchev         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# one:
# 	gcc k_readline.c -lreadline libft.a && ./a.out

signals:
	gcc k_signals.c -lreadline libft.a && ./a.out
	
test:
	# $(MAKE) clean -C ../42_libft
	# $(MAKE) -C ../42_libft
	gcc parse_input.c -L../42_libft -l:libft.a